- hosts: home_server
  become: true
  tasks:
    - name: install some packages
      apt:
        name:
          - unzip
          - zip
        state: latest
        update_cache: yes
    - name: install packages for docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
        update_cache: yes
    - name: add docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: verify docker's official GPG key
      shell: apt-key fingerprint 0EBFCD88 | grep "9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88"
      environment:
        # suppress warning "apt-key output should not be parsed (stdout is not a terminal)"
        APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
    - name: get lsb_release
      shell: lsb_release -cs
      register: lsb_release
    - name: add docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
        state: present
    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
    - name: run docker at starting os
      systemd:
        name: docker
        enabled: yes
        masked: no
    - name: manage docker as a non-root user
      group:
        name: docker
        state: present
    - name: add user 'loca' to docker group
      user:
        name: loca
        groups: docker
        append: yes
    - name: check docker-compose installed
      stat:
        path: /usr/local/bin/docker-compose
      register: docker_compose
    - name: check docker-compose version
      shell: docker-compose --version
      register: check_dc_version_result
      when: docker_compose.stat.exists
    - name: install docker compose
      get_url:
        url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x,o+x'
        force: yes
      when: not docker_compose.stat.exists or docker_compose_version not in check_dc_version_result.stdout
    - name: set alias for docker compose
      lineinfile:
        path=/home/loca/.bashrc
        line="alias dc='docker-compose'"
        state=present
