- name: Install qemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: latest
    update_cache: yes
- name: Start qemu-guest-agent
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started
