- name: Disable enterprise repository
  replace:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com(.+)'
    replace: '#deb https://enterprise.proxmox.com\1'
- name: Enable no-subscription repository
  blockinfile:
    path: /etc/apt/sources.list
    block: |
      # PVE pve-no-subscription repository provided by proxmox.com,
      # NOT recommended for production use
      deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
