- name: Disable default pool
  replace:
    path: /etc/chrony/chrony.conf
    regexp: "pool(.*)"
    replace: "#pool\\g<1>"
- name: Add NTP server sources
  copy:
    content: "server router-main.network.home iburst\n"
    dest: /etc/chrony/sources.d/local.sources
    owner: root
    group: root
    mode: "0644"
- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
    daemon_reload: yes
