- name: Install packages for docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: latest
    update_cache: yes
- name: Add docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Verify docker's official GPG key
  shell: apt-key fingerprint 0EBFCD88 | grep "9DC8 5822 9FC7 DD38 854A  E2D8 8D81 803C 0EBF CD88"
  environment:
    # suppress warning "apt-key output should not be parsed (stdout is not a terminal)"
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: 1
- name: Get lsb_release
  shell: lsb_release -cs
  register: lsb_release
- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable
    state: present
- name: Install docker
  apt:
    name:
      - "docker-ce={{ docker_ce_version }}"
      - "docker-ce-cli={{ docker_ce_version }}"
      - "containerd.io"
    state: present
    update_cache: yes
- name: Run docker at starting os
  systemd:
    name: docker
    enabled: yes
    masked: no
- name: Manage docker as a non-root user
  group:
    name: docker
    state: present
- name: Add user to docker group
  user:
    name: "{{ user_of_docker_group }}"
    groups: docker
    append: yes
